using System.Collections.Generic;
using SQLite;

namespace aqq
{

    public class Details{

        public string Email { get; set; }
        public string Phone { get; set; }
        public string Skill { get; set; }
		public string Name { get; set; }
		public string Postcode { get; set; }
        public string Status { get; set; }
		
    }

   








    public class LocalData
    {
        public List<string> librarylist;
        public LocalData()
        {

            librarylist = new List<string> {

"Alexandra Library",
"Altona Library",
"Altona Meadows Library",
"Ararat Library",
"Ascot Vale Library",
"Ashburton Library",
"Avoca Library",
"Bacchus Marsh Library",
"Bairnsdale Library",
"Ballarat Library",
"Balwyn Library",
"Barham Library",
"Barwon Heads Library",
"Beaufort Library",
"Beaumaris Library",
"Beechworth Library",
"Belgrave Library",
"Belmont Library",
"Benalla Library",
"Bendigo Library",
"Bentleigh Library",
"Birchip Library",
"Blackburn Library",
"Boronia Library",
"Box Hill Library",
"Bright Library",
"Brighton Library",
"Broadford Library",
"Brunswick Library",
"Bulleen Library",
"Camberwell Library",
"Campbell Turnbull Library",
"Camperdown Library",
"Carlton Library",
"Carnegie Library",
"Carrum Downs Library",
"Casterton Library",
"Castlemaine Library",
"Caulfield Library",
"Chelsea Library",
"Cheltenham Library",
"Chiltern Library",
"Chilwell Library",
"Churchill Library",
"Cinemedia Library",
"City Library",
"Clarinda Library",
"Clayton Library",
"Clunes Library",
"Cobden Library",
"Cobram Secondary College Community Library",
"Coburg Library",
"Cohuna Library",
"Colac Library",
"Colbinabbin Library",
"Collingwood Library",
"Corio Library",
"Corowa Library",
"Corryong Library",
"Craigieburn Library",
"Cranbourne Library",
"Creswick Library",
"Croydon Library",
"Dandenong Library",
"Daylesford Library",
"Deer Park Library",
"Derrinallum Library",
"Diamond Valley Library",
"Dimboola Library",
"Dingley Library",
"Doveton Library",
"Drouin Library",
"Drysdale Library",
"Eaglehawk Mechanics' Institute Library",
"East Keilor Library",
"East Melbourne Library",
"Echuca Library",
"Edenhope Library",
"Elsternwick Library",
"Eltham Library",
"Emerald Library",
"Emerald Hill Library",
"Endeavour Hills Library",
"Euroa Public Library",
"Fairfield Library",
"Fawkner Library",
"Ferntree Gully Library",
"Fitzroy Library",
"Flemington Library",
"Footscray Library",
"Footscray West Library",
"Foster Library",
"Frankston Library",
"Geelong Library",
"Geelong West Library",
"Girgarre Library",
"Gisborne Library",
"Gladstone Park Library",
"Glenroy Library",
"Glen Waverley Library",
"Goroke Library",
"Grovedale Library",
"Gunbower Library",
"Hamilton Library",
"Hampton Library",
"Hampton Park Library",
"Harrow Library",
"Hastings Library",
"Hawthorn Library",
"Healesville Library",
"Heathcote Library",
"Heyfield Library",
"Heywood Library",
"Highett Library",
"Highpoint Shopping Centre Library",
"Highton Library",
"Holbrook Library",
"Horsham Library",
"Inverloch Library",
"Irymple Library",
"Ivanhoe Library",
"Kangaroo Flat Library",
"Kaniva Library",
"Keilor Library",
"Kerang Library",
"Kew Library",
"Kilmore Library",
"Kinglake Library",
"Knox Library",
"Koroit Library",
"Korumburra Library",
"Kyabram Library",
"Kyneton Library",
"Lakes Entrance Library",
"Lalor Library",
"Langwarrin Shop Library",
"Lavington Library",
"Leitchville Library",
"Leongatha Library",
"Lilydale Library",
"Lockington Library",
"Maffra Library",
"Mallacoota Library",
"Malvern Library",
"Manningham e-Library Centre at Warrandyte",
"Mansfield Library",
"Maryborough Library",
"Melton Library",
"Merbein Library",
"Middle Park Library",
"Mildura Library",
"Mill Park Library",
"Mirboo North Library",
"Moe Library",
"Montrose Library",
"Moonee Ponds Library",
"Moorabbin Library",
"Mooroolbark Library",
"Mooroopna Secondary College Community Library",
"Mornington Library",
"Mortlake Library",
"Morwell Library",
"Mount Evelyn Library",
"Mount Waverley Library",
"Mt Beauty Library",
"Myrtleford Library",
"Narre Warren Library",
"Nathalia Community Library",
"Neerim South Library",
"Newcomb Library",
"Newport Library",
"Newtown Library",
"Nhill Library",
"Niddrie Library",
"Noojee Library",
"Northcote Library",
"North Fitzroy Library",
"North Melbourne Library",
"Numurkah Public Library",
"Nunawading Library",
"Oakleigh Library",
"Ocean Grove Library",
"Omeo Library",
"Orbost Library",
"Pakenham Library",
"Parkdale Library",
"Paynesville Library",
"Phillip Island Library",
"Phoenix Park Library",
"Poowong Library",
"Port Fairy Library",
"Portland Library",
"Port Melbourne Library",
"Prahran /Windsor Library",
"Preston Library",
"Pyramid Hill - Library Express",
"Queenscliff Library",
"Red Cliffs Library",
"Reservoir Library",
"Richmond Library",
"Ringwood Library",
"Rochester Library",
"Rosanna Library",
"Rosebud Library",
"Rosedale Library",
"Rowville Library",
"Rushworth Library",
"Rutherglen Library",
"RVIB Library",
"Sale Library",
"Sandringham Library",
"Seaford Shop Library",
"Sebastopol Library",
"Seymour Library",
"Shepparton Library",
"Doncaster Library",
"Somerville Library",
"South Oakleigh Library",
"Springvale Library",
"St Albans Library",
"Stanhope Library",
"St Arnaud Library",
"State Library",
"Stawell Library",
"St Kilda Library",
"Stockland Shopping Centre Library",
"Stratford Library",
"Sunbury Library",
"Sunshine Library",
"Swan Hill Library",
"Tallangatta Library",
"Tatura Public Library",
"Terang Library",
"The Age Library Broadmeadows Library",
"The Pines Library",
"Thomastown Library",
"Timboon Library",
"Tongala Library",
"Toorak/South Yarra Library",
"Torquay Library",
"Traralgon Library",
"Tullamarine Library",
"Vermont South Library",
"Violet Town Public Library",
"Vision Australia Library",
"Wallan Library",
"Wangaratta Library",
"Warracknabeal Library",
"Warragul Library",
"Warrnambool Library",
"Watsonia Library",
"Werribee Library",
"Werribee CBD Library",
"Wheelers Hill Library",
"Williamstown Library",
"Wodonga Library",
"Wonthaggi Library",
"Woodend Library",
"Yarra Junction Library",
"Yarram Library",
"Yarraville Library",
"Yarrawonga Public Library",
"Yea Library"


        };
        }



    }

}
